apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftp-users-app
  labels:
    app.kubernetes.io/name: sftp-users-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sftp-users-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sftp-users-app
    spec:
      imagePullSecrets:
        - name: image-pull-secret
      containers:
        - name: smarttransfer
          image: docker.totvs.io/renato.cerqueira/sftp-users:{{ .Values.version }}
          imagePullPolicy: IfNotPresent
          env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          ports:
          - containerPort: 3000
            protocol: TCP
          volumeMounts:
            - mountPath: /etc/sftp/users
              name: usersconf
              readOnly: true
      volumes:
        - name: usersconf
          configMap:
            defaultMode: 0420
            name: sftp-users
---
apiVersion: v1
kind: Service
metadata:
  name: http-users
spec:
  selector:
    app.kubernetes.io/name: sftp-users-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
